In [1]:
import importlib
import clusters
importlib.reload(clusters)
from clusters import *

In [4]:
# combine each cluster's data into a single DataFrame, with a new column for the cluster name
combined = pd.concat([c.data.assign(cluster=c.name) for c in clusters])
combined

,source_id,bp_rp,phot_g_mean_mag,bp_g,g_rp,phot_g_mean_flux,cluster
0,5318501987408551936,1.381412,16.326288,0.607067,0.774344,5556.883910,IC 2391
1,5318501918689059712,0.827928,13.318416,0.331872,0.496056,88711.555917,IC 2391
2,5318501884329334272,0.879195,13.852233,0.353294,0.525901,54256.649720,IC 2391
3,5318501849969589632,0.920446,14.369488,0.375167,0.545280,33693.897323,IC 2391
4,5318501781250125440,1.168430,16.150420,0.493393,0.675037,6533.995236,IC 2391
...,...,...,...,...,...,...,...
848,2019231221592376704,1.558789,15.330036,0.724684,0.834106,13910.149975,NGC 6793
849,2019068012830442240,1.361452,14.868836,0.606741,0.754711,21272.159526,NGC 6793
850,2019162261557518080,2.605521,17.281424,1.322830,1.282691,2305.562682,NGC 6793
851,2019136938468058624,1.911334,16.222893,0.946844,0.964490,6112.080725,NGC 6793
852,2019168751257810176,2.204772,11.942986,1.156009,1.048763,314884.764511,NGC 6793

In [5]:
# write out
combined.to_csv("cache/combined.csv", index=False)